### ISSUE TITLE
表單

### ISSUE THREAD

**Issue by gwe9001** [chrisliuqq/chrisliuqq.github.io#1]
下面的連結可以加巴哈區的連結
表單直接POST(已測試可以)，提交後顯示訊息表示已傳送，清空表單繼續輸入
3種表單可以3個連結或彈出後選擇
錯誤回報可以直接帶出題目答案甚至是類型，顏色數量。
可以參考
http://cxz9001.github.io/wiz-tw/
自己依樣畫葫蘆改出來的，畢竟才大二

**Comment by cxz9001** [comment]
每日問答的表單https://docs.google.com/forms/d/19ON61ZicDwCDxIqujvXv4baYCQ1NzWPrQxbinVh0bAA/viewform?c=0&w=1


用素材時間表的方式會更直覺，一點開就可以直接填，不用開分頁也不用往下拖

**Comment by chrisliuqq** [comment]
現在才看到 XD 不過昨天晚上已經加上去啦～
感謝提供！
