### ISSUE TITLE
四題排序

### ISSUE THREAD

**Issue by tacticalandy** [chrisliuqq/chrisliuqq.github.io#2]
請將下列出現在中美洲且曾經繁盛過的文明依順序由先至後排列。
奧爾梅克文明、馬雅文明、迪奧狄華肯文明、阿茲特克文明

答案是錯的，可是查GOOGLE卻應該是這樣排沒錯....

**Comment by tacticalandy** [comment]
請將下列出現在中美州且曾經繁盛過的文明依順序由先至後排列
奧爾梅克文明、迪奧狄華肯文明、馬雅文明、阿茲特克文明

這視另外一個答案，沒試過

**Comment by gwe9001** [comment]
題庫問題要到
https://docs.google.com/forms/d/1GYyqSKOfF2KMkMGfEuKtyE8oZadgTRRj_ZClYZRX2Qc/viewform
回報
這裡是網頁問題

**Comment by chrisliuqq** [comment]
是的，題庫要到樓上提供的網址回報喔！！
